add full hw-02
maksnovakov/nodejs-homework-rest-api pull request #3
Opened 2023-01-25 12:32 UTC by maksnovakov

Добрый день, Александр! отправляю на проверку дз 2! Спасибо1

2023-01-25 18:42 UTC, Eastvarga requested changes
Є зауваження

2023-01-25 18:42 UTC, Eastvarga commented on bin/server.js
> +  console.log(`Server running. Use our API on port: ${PORT}`);
Для чого цей дублюючий модуль?

2023-01-25 18:42 UTC, Eastvarga commented on models/contacts.js
> +  const newContacts = contacts.filter(({ id }) => id.toString() !== contactId);
Видалення контакту можна зробити одним методом масиву, а не двома.

2023-01-25 18:42 UTC, Eastvarga commented on models/contacts.js
> +  contacts[index] = { ...contacts[index], ...body };
спробуйте реалізувати апдейт використовуючи  метод масиву map

2023-01-25 18:42 UTC, Eastvarga commented on routes/api/contacts.js
> +router.patch("/:contactId", validate.updateContact, async (req, res, next) => {
А який метод повинен бути по завданню? - не відповідає завданню

2023-01-25 18:42 UTC, Eastvarga commented on routes/api/validation.js
> +    .optional(),
Для створення, по завданню, обов'язкові усі поля

2023-01-25 18:42 UTC, Eastvarga commented on routes/api/validation.js
> +});
ось тут не вистачає умови що кине помилку коли не буде жодного поля у тілі запиту .min(1) наприклад

2023-01-25 18:42 UTC, Eastvarga commented on routes/api/validation.js
> +module.exports.createContact = (req, res, next) => {
Якесь дивне використання мідлвару. Ім'я змінної createContact  не відповідає тому що робить її функція

2023-01-25 18:42 UTC, Eastvarga commented on routes/api/contacts.js
>  router.get("/", async (req, res, next) => {
async (req, res, next) => 
цей запис зазвичай використовується для мідлварів
async (req, res)=>
цей запис зазвичай вказує на останній сервіс, котрий виконує/містить бізнес логіку
router.get("/", someMiddleware1(req, res, next),someMiddleware2(req, res, next),someMiddleware3(req, res, next),finalService(req, res) )

2023-01-27 18:51 UTC, Eastvarga requested changes
Є зауваження

2023-01-27 18:51 UTC, Eastvarga commented on models/contacts.js
> +  contacts[idx] = { ...{ id: `${contactId}`, name, email, phone } };
Погана реалызація, чому не читаєте коментарі? Чи Ви пробували реалізувати апдейт за допомогою методу map()?
Чи мої коментарі Вам зрозумілі?

2023-01-27 18:51 UTC, Eastvarga commented on routes/api/contacts.js
> +  }),
а де .required() для поля пошти?
Вам треба винести схеми валідації до окремого файлу, а саму валідацію винести до мідлвару котрий використовувати там де потрібно.

2023-01-27 18:51 UTC, Eastvarga commented on routes/api/contacts.js
>  router.get("/", async (req, res, next) => {
Чому немає реакції на моє зауваження що до форми запису контролера?

2023-01-27 18:51 UTC, Eastvarga commented on routes/api/contacts.js
> +    return res.json({ contacts });
res.json(contacts); цього достатньо

2023-01-27 18:51 UTC, Eastvarga commented on routes/api/contacts.js
> +    });
Достатньо res.status(200).json(result)

2023-01-27 18:51 UTC, Eastvarga commented on routes/api/contacts.js
> -router.post("/", validate.createContact, async (req, res, next) => {
createContactValidation - лостатньо було перейменувати коректно функцію, та у контроллері 
 (req, res, **next**)  - зайвий  **next**

2023-01-27 18:51 UTC, Eastvarga commented on routes/api/contacts.js
>      });
стільки зайвих рухів,  res.status(201).json(result) достатньо для відповіді

2023-01-27 18:51 UTC, Eastvarga commented on routes/api/contacts.js
> +    const result = await contactsOptions.removeContact(contactId);
а чому не імпортували самі  функції  - removeContact(contactId) навіщо імпортуєте об'єктом contactsOptions - по назві це, до речі не має бути Options бо опції це налаштування, доречніше вже Actions буде. Вчіться доречно іменувати функції та об'єкти.

2023-01-27 18:51 UTC, Eastvarga commented on routes/api/contacts.js
> +    });
тоді можна і data-data-data.....-data вкладеність робити, але навіщо така дивна вкладеність - не зрозуміло

2023-01-27 18:51 UTC, Eastvarga commented on routes/api/contacts.js
> -router.patch("/:contactId", validate.updateContact, async (req, res, next) => {
validate.updateContact - зробіть updateContactValidation, хіба я казав прибирати цей мідлвар? Я казав про недоречне іменування

2023-02-01 11:48 UTC, maksnovakov commented on models/contacts.js
> +  contacts[idx] = { ...{ id: `${contactId}`, name, email, phone } };
не зовсім зрозумілі,бо немає того досвіду ,якого хотілося б, якби це навчання не тільки онлайн ,то було б зрозумілішим. немає достатньо часу, бо є сімья та робота. прошу бути трохи лояльнішим. чи можліво якісь конркетні примери ви могли б порекомендувати. дякую. чи можливо ви знаходитесь у Харкові, і могли б мені надати декілька допуроків по розьясненню? буду переробляти. гарного дня.

2023-02-02 20:48 UTC, Eastvarga approved these changes

2023-02-02 20:48 UTC, merged