hw05
maksnovakov/nodejs-homework-rest-api pull request #6
Opened 2023-02-26 15:41 UTC by maksnovakov

2023-02-26 16:54 UTC, Eastvarga requested changes
Є зауваження

2023-02-26 16:54 UTC, Eastvarga commented on controllers/users/avatars.js
> +  const [extension] = originalname.spplit(".").reverse();
дивно, невже все працює? Ви впевнені що не припустились маленької помилки?

2023-02-26 16:54 UTC, Eastvarga commented on controllers/users/avatars.js
> +  const avatarURL = path.join("avatars", fileName);
невірно, генерація урла за допомогою пакету призначеного для файлової системи має один критичний недолік - у різних операційних системах генеруватись будуть різні строки.
тому краще \`/avatars/${filename}`

2023-02-28 17:45 UTC, maksnovakov commented on controllers/users/avatars.js
> +  const avatarURL = path.join("avatars", fileName);
якщо я правільно вас зрозумів, то тоді виправив.

2023-02-28 19:17 UTC, Eastvarga requested changes
Є зауваження

2023-02-28 19:17 UTC, Eastvarga commented on controllers/users/avatars.js
> +  const avatarURL = path.join(`/avatars/${fileName}`);
OMG не гібкість мислення це дуже погано
const avatarURL = \`http://localhost:${PORT}/avatars/${fileName}`; на реакті повинні були зтикатись з подібним

2023-03-01 13:54 UTC, maksnovakov commented on controllers/users/avatars.js
> +  const avatarURL = path.join(`/avatars/${fileName}`);
трохи заплутався, яку помілку брудну зробив-сорі!

2023-03-01 19:08 UTC, Eastvarga approved these changes

2023-03-01 19:08 UTC, merged